name: CI

on:
  push:
    branches: [ "master", "dev" ]

jobs:
  linux-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        configuration: [Debug, Release]
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v3
  
    - name: Install clang
      run: apt update && apt install clang
  
    - name: Build
      run: mkdir build && cd build && cmake -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} .. && make

  windows-build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
  
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main
  
    - name: Build
      run: mkdir build && cd build && cmake ..
    
    - name: Folder
      run: cd build && dir
