name: CI

on:
  push:
    branches: [ "master", "dev" ]

jobs:
  linux-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        configuration: [Debug, Release]
        compiler: [g++, clang++]

    steps:
    - uses: actions/checkout@v3
  
    - name: Build
      run: mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} .. && make

  windows-build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v3
  
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@main
  
    - name: Build
      run: mkdir build && cd build && cmake .. && msbuild /p:Configuration=${{ matrix.configuration }} /p:Platform=x64 ALL_BUILD.vcxproj
    
    - name: Folder
      run: cd build && cd x64 && cd ${{ matrix.configuration }} && dir

  linux-docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Install docker
      run: sudo apt install docker -y

    - name: Pull Ubuntu 18.04
      run: sudo docker pull ubuntu:18.04

    - name: Run docker
      run: docker run --rm -it ubuntu:18.04
